server:
  port: 8081
  servlet:
    path: /movie-api/*

spring:
  application:
    name: microservice-consumer-movie
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user-service:
  #  microservice-provider-user是用户微服务的虚拟主机名
  url: http://microservice-provider-user/user-api/user/
  application: microservice-provider-user

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@localhost:8764/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

# 将负载均衡规则修改为随机
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    脱离Eureka使用Ribbon
#    listOfServers: localhost:8082,localhost:8083

ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
logging:
  level:
    com.nsk.cloud.microservicesimpleconsumermovie.user.UserFeignClient: DEBUG
