server:
  port: 8081
  servlet-path: /movie-api/*

spring:
  profiles:
    active: dev
  application:
    name: microservice-consumer-movie
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

user-service:
  url: http://localhost:8080/user-api/user/

eureka:
  client:
    service-url:
#      default-zone: http://nsk:abcd1234@localhost:8763/eureka/
      default-zone: http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
